kind: pipeline
name: default

steps:
- name: P68
  image: python:3
  commands:
  - apt update
  - apt install -y git
  - git submodule update --init --recursive
  - pip install -U https://github.com/OS-Q/S03/archive/master.zip
  - qio platform install file://.
  - qio run -d examples/arduino-blink
  - qio run -d examples/gpio-blink
  - qio run -d examples/adc-example
  - qio run -d examples/ssl-socket-example
  - qio run -d examples/socket-example
  - qio run -d examples/ssl-socket-clientauth
