language: python
python:
  - "3.7"

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink
  - PLATFORMIO_PROJECT_DIR=examples/gpio-blink
  - PLATFORMIO_PROJECT_DIR=examples/adc-example
  - PLATFORMIO_PROJECT_DIR=examples/socket-example
  - PLATFORMIO_PROJECT_DIR=examples/ssl-socket-example
  - PLATFORMIO_PROJECT_DIR=examples/ssl-socket-clientauth

install:
  - pip install -U https://github.com/OS-Q/S03/archive/master.zip
  - pio platform install file://.

script:
  - pio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email:
    recipients:
      - tang@qitas.cn
    on_success: never # default: change
    on_failure: always # default: always
