language: python
python:
  - "3.9"
os:
  - linux

git:
  depth: 1

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink
  - PLATFORMIO_PROJECT_DIR=examples/gpio-blink
  - PLATFORMIO_PROJECT_DIR=examples/adc-example
  - PLATFORMIO_PROJECT_DIR=examples/socket-example
  - PLATFORMIO_PROJECT_DIR=examples/ssl-socket-example
  - PLATFORMIO_PROJECT_DIR=examples/ssl-socket-clientauth

install:
  - pip install platformio
    pio update
  - pio platform install file://.

script:
  - pio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
