build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/adc-example"
    - PLATFORMIO_PROJECT_DIR: "examples/gpio-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/socket-example"
    - PLATFORMIO_PROJECT_DIR: "examples/ssl-socket-example"
    - PLATFORMIO_PROJECT_DIR: "examples/ssl-socket-clientauth"

install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\Python37\Scripts;%PATH%
  - cmd: pip3 install -U https://github.com/OS-Q/S03/archive/master.zip
  - cmd: pio platform install file://.

test_script:
  - cmd: pio run -d %PLATFORMIO_PROJECT_DIR%

