version: 2
jobs:
  PIO:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "System"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
      - run:
          name: "Install"
          command: |
            python -m pip install --upgrade pip
            pip install -U https://github.com/platformio/platformio/archive/develop.zip
            pio platform install file://.
      - run:
          name: "Build"
          command: |
            pio run -d examples/arduino-blink
            pio run -d examples/gpio-blink
            pio run -d examples/adc-example
            pio run -d examples/ssl-socket-example
            pio run -d examples/socket-example
            pio run -d examples/ssl-socket-clientauth

  QIO:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "System"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
      - run:
          name: "Install"
          command: |
            python -m pip install --upgrade pip
            pip install -U https://github.com/OS-Q/S03/archive/master.zip
            qio platform install file://.
      - run:
          name: "Build"
          command: |
            pio run -d examples/arduino-blink
            pio run -d examples/gpio-blink
            pio run -d examples/adc-example
            pio run -d examples/ssl-socket-example
            pio run -d examples/socket-example
            pio run -d examples/ssl-socket-clientauth

workflows:
    version: 2
    run_ci:
        jobs:
            - PIO
            - QIO
