name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

env:
  UPLOAD_BUILD: true

jobs:
  build:
    if: github.repository == 'OS-Q/P68'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: [3.9]
        tool:
          - "PIO"
          - "QIO"
        examples:
          - "examples/arduino-blink"
          - "examples/gpio-blink"
          - "examples/adc-example"
          - "examples/socket-example"
          - "examples/ssl-socket-example"
          - "examples/ssl-socket-clientauth"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install PIO
        if: matrix.tool == 'PIO'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio platform install file://.

      - name: Install QIO
        if: matrix.tool == 'QIO'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          qio platform install file://.

      - name: Build
        id: build
        if: success()
        run: |
          pio run -d ${{ matrix.examples }}
          echo "::set-output name=status::success"

      - name: Upload
        if: steps.build.outputs.status == 'success' && matrix.tool == 'QIO'
        uses: actions/upload-artifact@v2
        with:
          name: P68
          path: ${{ matrix.examples }}
