name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

env:
  UPLOAD_BUILD: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        examples:
          - "gpio-blink"
          - "adc-example"
          - "arduino-blink"
          - "socket-example"
          - "ssl-socket-example"
          - "ssl-socket-clientauth"
        # os: [ubuntu-latest]


    runs-on: ubuntu-latest #${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install
        if: github.repository == 'OS-Q/P68'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          qio platform install file://.

      - name: Build
        id: build
        if: success()
        run: |
          mkdir examples/${{ matrix.examples }}/build
          pio run -d examples/${{ matrix.examples }} > examples/${{ matrix.examples }}/build/log.txt
          echo "::set-output name=status::success"

      - name: Upload
        if: steps.build.outputs.status == 'success' && env.UPLOAD_BUILD
        uses: actions/upload-artifact@v2
        with:
          name: P68_${{ matrix.examples }}
          path: examples/${{ matrix.examples }}/build
