name: P69

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7]
        example:
          - "examples/arduino-blink"
          - "examples/gpio-blink"
          - "examples/adc-example"
          - "examples/socket-example"
          - "examples/ssl-socket-example"
          - "examples/ssl-socket-clientauth"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          platformio platform install file://.
      - name: Build
        run: |
          platformio run -d ${{ matrix.example }}
